# Generated by Django 5.2.7 on 2025-10-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Inventory',
            fields=[
                ('Plate_No', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Car_Model', models.CharField(max_length=100)),
                ('Car_Type', models.CharField(max_length=20)),
                ('Mileage', models.IntegerField()),
                ('Engine_Type', models.CharField(max_length=15)),
                ('Make_Date', models.DateField()),
                ('Car_color', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
